version: '3'

services:
  google-chrome-puppeteer:
    build: .
    container_name: google-chrome-puppeteer
    volumes:
    # mount code and output directories into the container
      - .:/app
    working_dir: /app
    shm_size: 1gb #512M
    # just run the container doing nothing
    entrypoint: ["sh", "-c", "sleep infinity"]
